<?php

namespace Ais\SlotBundle\Repository;

/**
 * SlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotRepository extends \Doctrine\ORM\EntityRepository
{
}
